# Generated by Django 3.2.7 on 2021-10-05 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('New_blog', '0003_alter_post_body'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='body',
            field=models.TextField(),
        ),
    ]
