# Generated by Django 3.2.7 on 2021-10-05 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('New_blog', '0004_alter_post_body'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
            ],
        ),
        migrations.AddField(
            model_name='post',
            name='category',
            field=models.CharField(default='coding', max_length=250),
        ),
    ]
