# Generated by Django 3.2.7 on 2021-10-06 11:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('New_blog', '0007_rename_body_post_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='title',
            new_name='place',
        ),
    ]
